const domains = ["https://autoconfig.thunderbird.net/v1.1/2die4.com",
"https://autoconfig.thunderbird.net/v1.1/2senior.dk",
"https://autoconfig.thunderbird.net/v1.1/12fuel.dk",
"https://autoconfig.thunderbird.net/v1.1/12mail.dk",
"https://autoconfig.thunderbird.net/v1.1/12move.dk",
"https://autoconfig.thunderbird.net/v1.1/123mail.dk",
"https://autoconfig.thunderbird.net/v1.1/126.com",
"https://autoconfig.thunderbird.net/v1.1/163.com",
"https://autoconfig.thunderbird.net/v1.1/1031.inord.dk",
"https://autoconfig.thunderbird.net/v1.1/a1.net",
"https://autoconfig.thunderbird.net/v1.1/abc.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/accountant.com",
"https://autoconfig.thunderbird.net/v1.1/active24.com",
"https://autoconfig.thunderbird.net/v1.1/activist.com",
"https://autoconfig.thunderbird.net/v1.1/adexec.com",
"https://autoconfig.thunderbird.net/v1.1/africamail.com",
"https://autoconfig.thunderbird.net/v1.1/agate.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/aim.com",
"https://autoconfig.thunderbird.net/v1.1/aircraftmail.com",
"https://autoconfig.thunderbird.net/v1.1/alabama.usa.com",
"https://autoconfig.thunderbird.net/v1.1/alaska.usa.com",
"https://autoconfig.thunderbird.net/v1.1/alice.it",
"https://autoconfig.thunderbird.net/v1.1/allergist.com",
"https://autoconfig.thunderbird.net/v1.1/alumni.com",
"https://autoconfig.thunderbird.net/v1.1/alumnidirector.com",
"https://autoconfig.thunderbird.net/v1.1/amail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/amber.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/americamail.com",
"https://autoconfig.thunderbird.net/v1.1/ameritech.net",
"https://autoconfig.thunderbird.net/v1.1/amethyst.broba.cc",
"https://autoconfig.thunderbird.net/v1.1/amorki.pl",
"https://autoconfig.thunderbird.net/v1.1/amorous.com",
"https://autoconfig.thunderbird.net/v1.1/anarki.dk",
"https://autoconfig.thunderbird.net/v1.1/anderledes.dk",
"https://autoconfig.thunderbird.net/v1.1/angelic.com",
"https://autoconfig.thunderbird.net/v1.1/aol.com",
"https://autoconfig.thunderbird.net/v1.1/aon.at",
"https://autoconfig.thunderbird.net/v1.1/apost.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/aqua.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/archaeologist.com",
"https://autoconfig.thunderbird.net/v1.1/arcor.de",
"https://autoconfig.thunderbird.net/v1.1/arizona.usa.com",
"https://autoconfig.thunderbird.net/v1.1/artlover.com",
"https://autoconfig.thunderbird.net/v1.1/arubapec.it",
"https://autoconfig.thunderbird.net/v1.1/asia-mail.com",
"https://autoconfig.thunderbird.net/v1.1/atheist.com",
"https://autoconfig.thunderbird.net/v1.1/att.net",
"https://autoconfig.thunderbird.net/v1.1/australiamail.com",
"https://autoconfig.thunderbird.net/v1.1/autograf.pl",
"https://autoconfig.thunderbird.net/v1.1/ballade.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/bartender.net",
"https://autoconfig.thunderbird.net/v1.1/bay.gunmanet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/bay.gunmanet.or.jp",
"https://autoconfig.thunderbird.net/v1.1/bay.wind.co.jp",
"https://autoconfig.thunderbird.net/v1.1/bay.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/bay.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/bb-niigata.jp",
"https://autoconfig.thunderbird.net/v1.1/bc.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/begavet.dk",
"https://autoconfig.thunderbird.net/v1.1/beige.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/belgacom.net",
"https://autoconfig.thunderbird.net/v1.1/bell.net",
"https://autoconfig.thunderbird.net/v1.1/bellsouth.net",
"https://autoconfig.thunderbird.net/v1.1/berlin.com",
"https://autoconfig.thunderbird.net/v1.1/bigger.com",
"https://autoconfig.thunderbird.net/v1.1/biglobe.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/bigpond.com",
"https://autoconfig.thunderbird.net/v1.1/bigpond.net",
"https://autoconfig.thunderbird.net/v1.1/bigpond.net.au",
"https://autoconfig.thunderbird.net/v1.1/bikerider.com",
"https://autoconfig.thunderbird.net/v1.1/birdlover.com",
"https://autoconfig.thunderbird.net/v1.1/bitnisse.dk",
"https://autoconfig.thunderbird.net/v1.1/bk.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/bk.ru",
"https://autoconfig.thunderbird.net/v1.1/blader.com",
"https://autoconfig.thunderbird.net/v1.1/blu.it",
"https://autoconfig.thunderbird.net/v1.1/blue.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/bluemail.ch",
"https://autoconfig.thunderbird.net/v1.1/bluewin.ch",
"https://autoconfig.thunderbird.net/v1.1/blueyonder.co.uk",
"https://autoconfig.thunderbird.net/v1.1/bmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/boardermail.com",
"https://autoconfig.thunderbird.net/v1.1/bol.com.br",
"https://autoconfig.thunderbird.net/v1.1/bolero.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/bp.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/bpost.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/brazilmail.com",
"https://autoconfig.thunderbird.net/v1.1/brew-master.com",
"https://autoconfig.thunderbird.net/v1.1/brown.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/btinternet.com",
"https://autoconfig.thunderbird.net/v1.1/btopenworld.com",
"https://autoconfig.thunderbird.net/v1.1/bu.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/buziaczek.pl",
"https://autoconfig.thunderbird.net/v1.1/california.usa.com",
"https://autoconfig.thunderbird.net/v1.1/californiamail.com",
"https://autoconfig.thunderbird.net/v1.1/camel.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/cameo.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/caress.com",
"https://autoconfig.thunderbird.net/v1.1/casema.nl",
"https://autoconfig.thunderbird.net/v1.1/catlover.com",
"https://autoconfig.thunderbird.net/v1.1/cc9.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/cek.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/centurylink.net",
"https://autoconfig.thunderbird.net/v1.1/centurytel.net",
"https://autoconfig.thunderbird.net/v1.1/cgl.ucsf.edu",
"https://autoconfig.thunderbird.net/v1.1/charter.com",
"https://autoconfig.thunderbird.net/v1.1/charter.net",
"https://autoconfig.thunderbird.net/v1.1/cheerful.com",
"https://autoconfig.thunderbird.net/v1.1/chef.net",
"https://autoconfig.thunderbird.net/v1.1/chello.nl",
"https://autoconfig.thunderbird.net/v1.1/chemist.com",
"https://autoconfig.thunderbird.net/v1.1/chinamail.com",
"https://autoconfig.thunderbird.net/v1.1/city.dk",
"https://autoconfig.thunderbird.net/v1.1/clds.net",
"https://autoconfig.thunderbird.net/v1.1/clerk.com",
"https://autoconfig.thunderbird.net/v1.1/cliffhanger.com",
"https://autoconfig.thunderbird.net/v1.1/clio.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/cloudnine-net.jp",
"https://autoconfig.thunderbird.net/v1.1/club-internet.fr",
"https://autoconfig.thunderbird.net/v1.1/clustermail.de",
"https://autoconfig.thunderbird.net/v1.1/cmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/cneweb.de",
"https://autoconfig.thunderbird.net/v1.1/co1.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/co1.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/co2.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/co2.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/co3.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/co3.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/coastalnow.net",
"https://autoconfig.thunderbird.net/v1.1/cochill.net",
"https://autoconfig.thunderbird.net/v1.1/cocoa.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/coda.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/collector.org",
"https://autoconfig.thunderbird.net/v1.1/columnist.com",
"https://autoconfig.thunderbird.net/v1.1/comcast.net",
"https://autoconfig.thunderbird.net/v1.1/comic.com",
"https://autoconfig.thunderbird.net/v1.1/computer4u.com",
"https://autoconfig.thunderbird.net/v1.1/concerto.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/consultant.com",
"https://autoconfig.thunderbird.net/v1.1/contractor.net",
"https://autoconfig.thunderbird.net/v1.1/cool.dk",
"https://autoconfig.thunderbird.net/v1.1/coolsite.net",
"https://autoconfig.thunderbird.net/v1.1/coral.broba.ccv",
"https://autoconfig.thunderbird.net/v1.1/coral.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/corp.mail.ru",
"https://autoconfig.thunderbird.net/v1.1/counsellor.com",
"https://autoconfig.thunderbird.net/v1.1/count.com",
"https://autoconfig.thunderbird.net/v1.1/couple.com",
"https://autoconfig.thunderbird.net/v1.1/courante.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/cox.net",
"https://autoconfig.thunderbird.net/v1.1/cpost.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/cream.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/cswnet.com",
"https://autoconfig.thunderbird.net/v1.1/cty-net.com",
"https://autoconfig.thunderbird.net/v1.1/cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/cutey.com",
"https://autoconfig.thunderbird.net/v1.1/cyber-wizard.com",
"https://autoconfig.thunderbird.net/v1.1/cyberdude.com",
"https://autoconfig.thunderbird.net/v1.1/cyberdude.dk",
"https://autoconfig.thunderbird.net/v1.1/cybergal.com",
"https://autoconfig.thunderbird.net/v1.1/cyberjunkie.dk",
"https://autoconfig.thunderbird.net/v1.1/dallasmail.com",
"https://autoconfig.thunderbird.net/v1.1/dan.gunmanet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/dan.gunmanet.or.jp",
"https://autoconfig.thunderbird.net/v1.1/dan.wind.co.jp",
"https://autoconfig.thunderbird.net/v1.1/dan.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/dan.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/dance.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/dbzmail.com",
"https://autoconfig.thunderbird.net/v1.1/dd.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/deliveryman.com",
"https://autoconfig.thunderbird.net/v1.1/diamond.broba.cc",
"https://autoconfig.thunderbird.net/v1.1/diplomats.com",
"https://autoconfig.thunderbird.net/v1.1/disciples.com",
"https://autoconfig.thunderbird.net/v1.1/dk-online.dk",
"https://autoconfig.thunderbird.net/v1.1/dk2net.dk",
"https://autoconfig.thunderbird.net/v1.1/dmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/doctor.com",
"https://autoconfig.thunderbird.net/v1.1/doglover.com",
"https://autoconfig.thunderbird.net/v1.1/dondominio.com",
"https://autoconfig.thunderbird.net/v1.1/doramail.com",
"https://autoconfig.thunderbird.net/v1.1/dr.com",
"https://autoconfig.thunderbird.net/v1.1/dublin.com",
"https://autoconfig.thunderbird.net/v1.1/e23.jp",
"https://autoconfig.thunderbird.net/v1.1/earthling.net",
"https://autoconfig.thunderbird.net/v1.1/earthlink.net",
"https://autoconfig.thunderbird.net/v1.1/ebony.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/elinstallatoer.dk",
"https://autoconfig.thunderbird.net/v1.1/elpasotel.net",
"https://autoconfig.thunderbird.net/v1.1/elsker.dk",
"https://autoconfig.thunderbird.net/v1.1/elvis.dk",
"https://autoconfig.thunderbird.net/v1.1/elvisfan.com",
"https://autoconfig.thunderbird.net/v1.1/emadisonriver.com",
"https://autoconfig.thunderbird.net/v1.1/emadisonriver.net",
"https://autoconfig.thunderbird.net/v1.1/email.com",
"https://autoconfig.thunderbird.net/v1.1/email.cz",
"https://autoconfig.thunderbird.net/v1.1/email.dk",
"https://autoconfig.thunderbird.net/v1.1/email.it",
"https://autoconfig.thunderbird.net/v1.1/email.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/emailsrvr.com",
"https://autoconfig.thunderbird.net/v1.1/embarqmail.com",
"https://autoconfig.thunderbird.net/v1.1/engineer.com",
"https://autoconfig.thunderbird.net/v1.1/englandmail.com",
"https://autoconfig.thunderbird.net/v1.1/europe.com",
"https://autoconfig.thunderbird.net/v1.1/europemail.com",
"https://autoconfig.thunderbird.net/v1.1/ewe.net",
"https://autoconfig.thunderbird.net/v1.1/ewetel.de",
"https://autoconfig.thunderbird.net/v1.1/execs.com",
"https://autoconfig.thunderbird.net/v1.1/fald.dk",
"https://autoconfig.thunderbird.net/v1.1/fan.com",
"https://autoconfig.thunderbird.net/v1.1/fantasy.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/fastwebnet.it",
"https://autoconfig.thunderbird.net/v1.1/fedt.dk",
"https://autoconfig.thunderbird.net/v1.1/feelings.com",
"https://autoconfig.thunderbird.net/v1.1/feminin.dk",
"https://autoconfig.thunderbird.net/v1.1/ff.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/film.dk",
"https://autoconfig.thunderbird.net/v1.1/financier.com",
"https://autoconfig.thunderbird.net/v1.1/fireman.net",
"https://autoconfig.thunderbird.net/v1.1/flamenco.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/flash.net",
"https://autoconfig.thunderbird.net/v1.1/florida.usa.com",
"https://autoconfig.thunderbird.net/v1.1/fmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/foni.net",
"https://autoconfig.thunderbird.net/v1.1/footballer.com",
"https://autoconfig.thunderbird.net/v1.1/forening.dk",
"https://autoconfig.thunderbird.net/v1.1/free.fr",
"https://autoconfig.thunderbird.net/v1.1/freenet.de",
"https://autoconfig.thunderbird.net/v1.1/fuga.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/gadefejer.dk",
"https://autoconfig.thunderbird.net/v1.1/gallatinriver.net",
"https://autoconfig.thunderbird.net/v1.1/gandi.net",
"https://autoconfig.thunderbird.net/v1.1/gardener.com",
"https://autoconfig.thunderbird.net/v1.1/garnet.broba.cc",
"https://autoconfig.thunderbird.net/v1.1/gason.dk",
"https://autoconfig.thunderbird.net/v1.1/gelsennet.de",
"https://autoconfig.thunderbird.net/v1.1/geologist.com",
"https://autoconfig.thunderbird.net/v1.1/germanymail.com",
"https://autoconfig.thunderbird.net/v1.1/giallo.it",
"https://autoconfig.thunderbird.net/v1.1/gigahost.dk",
"https://autoconfig.thunderbird.net/v1.1/gigapec.it",
"https://autoconfig.thunderbird.net/v1.1/gmail.com",
"https://autoconfig.thunderbird.net/v1.1/gmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/gmx.at",
"https://autoconfig.thunderbird.net/v1.1/gmx.biz",
"https://autoconfig.thunderbird.net/v1.1/gmx.ca",
"https://autoconfig.thunderbird.net/v1.1/gmx.ch",
"https://autoconfig.thunderbird.net/v1.1/gmx.cn",
"https://autoconfig.thunderbird.net/v1.1/gmx.co.in",
"https://autoconfig.thunderbird.net/v1.1/gmx.co.uk",
"https://autoconfig.thunderbird.net/v1.1/gmx.com",
"https://autoconfig.thunderbird.net/v1.1/gmx.com.br",
"https://autoconfig.thunderbird.net/v1.1/gmx.com.my",
"https://autoconfig.thunderbird.net/v1.1/gmx.com.tr",
"https://autoconfig.thunderbird.net/v1.1/gmx.de",
"https://autoconfig.thunderbird.net/v1.1/gmx.es",
"https://autoconfig.thunderbird.net/v1.1/gmx.eu",
"https://autoconfig.thunderbird.net/v1.1/gmx.fr",
"https://autoconfig.thunderbird.net/v1.1/gmx.hk",
"https://autoconfig.thunderbird.net/v1.1/gmx.ie",
"https://autoconfig.thunderbird.net/v1.1/gmx.info",
"https://autoconfig.thunderbird.net/v1.1/gmx.it",
"https://autoconfig.thunderbird.net/v1.1/gmx.li",
"https://autoconfig.thunderbird.net/v1.1/gmx.net",
"https://autoconfig.thunderbird.net/v1.1/gmx.org",
"https://autoconfig.thunderbird.net/v1.1/gmx.ph",
"https://autoconfig.thunderbird.net/v1.1/gmx.pt",
"https://autoconfig.thunderbird.net/v1.1/gmx.ru",
"https://autoconfig.thunderbird.net/v1.1/gmx.se",
"https://autoconfig.thunderbird.net/v1.1/gmx.sg",
"https://autoconfig.thunderbird.net/v1.1/gmx.tm",
"https://autoconfig.thunderbird.net/v1.1/gmx.tw",
"https://autoconfig.thunderbird.net/v1.1/gmx.us",
"https://autoconfig.thunderbird.net/v1.1/go.tvm.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/go2.pl",
"https://autoconfig.thunderbird.net/v1.1/go4more.de",
"https://autoconfig.thunderbird.net/v1.1/goneo.de",
"https://autoconfig.thunderbird.net/v1.1/goo.jp",
"https://autoconfig.thunderbird.net/v1.1/google.com",
"https://autoconfig.thunderbird.net/v1.1/googlemail.com",
"https://autoconfig.thunderbird.net/v1.1/graduate.org",
"https://autoconfig.thunderbird.net/v1.1/gransy.com",
"https://autoconfig.thunderbird.net/v1.1/grape.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/graphic-designer.com",
"https://autoconfig.thunderbird.net/v1.1/gray.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/grics.net",
"https://autoconfig.thunderbird.net/v1.1/grin.dk",
"https://autoconfig.thunderbird.net/v1.1/grov.dk",
"https://autoconfig.thunderbird.net/v1.1/gulftel.com",
"https://autoconfig.thunderbird.net/v1.1/hackermail.com",
"https://autoconfig.thunderbird.net/v1.1/hahah.nl",
"https://autoconfig.thunderbird.net/v1.1/hairdresser.net",
"https://autoconfig.thunderbird.net/v1.1/hal.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/hana.or.jp",
"https://autoconfig.thunderbird.net/v1.1/hardworking.dk",
"https://autoconfig.thunderbird.net/v1.1/heaven.dk",
"https://autoconfig.thunderbird.net/v1.1/hemmelig.dk",
"https://autoconfig.thunderbird.net/v1.1/hh.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/hilarious.com",
"https://autoconfig.thunderbird.net/v1.1/hockeymail.com",
"https://autoconfig.thunderbird.net/v1.1/home.nl",
"https://autoconfig.thunderbird.net/v1.1/homemail.com",
"https://autoconfig.thunderbird.net/v1.1/hot-shot.com",
"https://autoconfig.thunderbird.net/v1.1/hotmail.co.jp",
"https://autoconfig.thunderbird.net/v1.1/hotmail.co.uk",
"https://autoconfig.thunderbird.net/v1.1/hotmail.com",
"https://autoconfig.thunderbird.net/v1.1/hotmail.com.br",
"https://autoconfig.thunderbird.net/v1.1/hotmail.de",
"https://autoconfig.thunderbird.net/v1.1/hotmail.es",
"https://autoconfig.thunderbird.net/v1.1/hotmail.fr",
"https://autoconfig.thunderbird.net/v1.1/hotmail.it",
"https://autoconfig.thunderbird.net/v1.1/hour.com",
"https://autoconfig.thunderbird.net/v1.1/huleboer.dk",
"https://autoconfig.thunderbird.net/v1.1/humanoid.net",
"https://autoconfig.thunderbird.net/v1.1/i.softbank.jp",
"https://autoconfig.thunderbird.net/v1.1/ic-net.or.jp",
"https://autoconfig.thunderbird.net/v1.1/iijmio-mail.jp",
"https://autoconfig.thunderbird.net/v1.1/iiyama-catv.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/illinois.usa.com",
"https://autoconfig.thunderbird.net/v1.1/image.dk",
"https://autoconfig.thunderbird.net/v1.1/imail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/iname.com",
"https://autoconfig.thunderbird.net/v1.1/inbound.dk",
"https://autoconfig.thunderbird.net/v1.1/inbox.lt",
"https://autoconfig.thunderbird.net/v1.1/inbox.lv",
"https://autoconfig.thunderbird.net/v1.1/inbox.ru",
"https://autoconfig.thunderbird.net/v1.1/indbakke.dk",
"https://autoconfig.thunderbird.net/v1.1/indigo.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/inet-shibata.or.jp",
"https://autoconfig.thunderbird.net/v1.1/infile.dk",
"https://autoconfig.thunderbird.net/v1.1/info.dk",
"https://autoconfig.thunderbird.net/v1.1/ingpec.eu",
"https://autoconfig.thunderbird.net/v1.1/innocent.com",
"https://autoconfig.thunderbird.net/v1.1/inorbit.com",
"https://autoconfig.thunderbird.net/v1.1/instruction.com",
"https://autoconfig.thunderbird.net/v1.1/instructor.net",
"https://autoconfig.thunderbird.net/v1.1/insurer.com",
"https://autoconfig.thunderbird.net/v1.1/internetserver.cz",
"https://autoconfig.thunderbird.net/v1.1/internode.on.net",
"https://autoconfig.thunderbird.net/v1.1/inwind.it",
"https://autoconfig.thunderbird.net/v1.1/io.dk",
"https://autoconfig.thunderbird.net/v1.1/iol.it",
"https://autoconfig.thunderbird.net/v1.1/ipax.at",
"https://autoconfig.thunderbird.net/v1.1/irelandmail.com",
"https://autoconfig.thunderbird.net/v1.1/ispgateway.de",
"https://autoconfig.thunderbird.net/v1.1/it.dk",
"https://autoconfig.thunderbird.net/v1.1/italymail.com",
"https://autoconfig.thunderbird.net/v1.1/ivory.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/iwafune.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/ix.netcom.com",
"https://autoconfig.thunderbird.net/v1.1/jade.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/janis.or.jp",
"https://autoconfig.thunderbird.net/v1.1/japan.com",
"https://autoconfig.thunderbird.net/v1.1/jazztel.es",
"https://autoconfig.thunderbird.net/v1.1/jet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/ji.jet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/jmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/journalist.com",
"https://autoconfig.thunderbird.net/v1.1/jyde.dk",
"https://autoconfig.thunderbird.net/v1.1/k1.gunmanet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/k1.gunmanet.or.jp",
"https://autoconfig.thunderbird.net/v1.1/k1.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/k1.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/kabelmail.de",
"https://autoconfig.thunderbird.net/v1.1/kelcom.net",
"https://autoconfig.thunderbird.net/v1.1/keromail.com",
"https://autoconfig.thunderbird.net/v1.1/khaki.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/kidcity.be",
"https://autoconfig.thunderbird.net/v1.1/kittymail.com",
"https://autoconfig.thunderbird.net/v1.1/kk.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/kl.gunmanet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/kl.gunmanet.or.jp",
"https://autoconfig.thunderbird.net/v1.1/kl.wind.co.jp",
"https://autoconfig.thunderbird.net/v1.1/kl.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/kl.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/klog.dk",
"https://autoconfig.thunderbird.net/v1.1/kmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/knus.dk",
"https://autoconfig.thunderbird.net/v1.1/kokuyou.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/koreamail.com",
"https://autoconfig.thunderbird.net/v1.1/krudt.dk",
"https://autoconfig.thunderbird.net/v1.1/kulturel.dk",
"https://autoconfig.thunderbird.net/v1.1/kundenserver.de",
"https://autoconfig.thunderbird.net/v1.1/lapis.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/laposte.net",
"https://autoconfig.thunderbird.net/v1.1/larsen.dk",
"https://autoconfig.thunderbird.net/v1.1/lawyer.com",
"https://autoconfig.thunderbird.net/v1.1/lazy.dk",
"https://autoconfig.thunderbird.net/v1.1/legislator.com",
"https://autoconfig.thunderbird.net/v1.1/lemon.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/libero.it",
"https://autoconfig.thunderbird.net/v1.1/lilac.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/lime.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/linuxmail.org",
"https://autoconfig.thunderbird.net/v1.1/list.ru",
"https://autoconfig.thunderbird.net/v1.1/live.co.jp",
"https://autoconfig.thunderbird.net/v1.1/live.co.uk",
"https://autoconfig.thunderbird.net/v1.1/live.com",
"https://autoconfig.thunderbird.net/v1.1/live.de",
"https://autoconfig.thunderbird.net/v1.1/live.fr",
"https://autoconfig.thunderbird.net/v1.1/live.it",
"https://autoconfig.thunderbird.net/v1.1/live.jp",
"https://autoconfig.thunderbird.net/v1.1/london.com",
"https://autoconfig.thunderbird.net/v1.1/loveable.com",
"https://autoconfig.thunderbird.net/v1.1/lovecat.com",
"https://autoconfig.thunderbird.net/v1.1/lystig.dk",
"https://autoconfig.thunderbird.net/v1.1/m2.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/m3.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/m4.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/m5.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/m6.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/m7.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/m8.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/m9.cty-net.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/ma100.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mac.com",
"https://autoconfig.thunderbird.net/v1.1/mad.scientist.com",
"https://autoconfig.thunderbird.net/v1.1/madisonriver.biz",
"https://autoconfig.thunderbird.net/v1.1/madonnafan.com",
"https://autoconfig.thunderbird.net/v1.1/madrid.com",
"https://autoconfig.thunderbird.net/v1.1/mahoroba.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mail.com",
"https://autoconfig.thunderbird.net/v1.1/mail.dia.dk",
"https://autoconfig.thunderbird.net/v1.1/mail.dk",
"https://autoconfig.thunderbird.net/v1.1/mail.gunmanet.jp",
"https://autoconfig.thunderbird.net/v1.1/mail.gunmanet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mail.gunmanet.or.jp",
"https://autoconfig.thunderbird.net/v1.1/mail.iwafune.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mail.org",
"https://autoconfig.thunderbird.net/v1.1/mail.ru",
"https://autoconfig.thunderbird.net/v1.1/mail.telenor.dk",
"https://autoconfig.thunderbird.net/v1.1/mail.wind.co.jp",
"https://autoconfig.thunderbird.net/v1.1/mail.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/mail.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/marchmail.com",
"https://autoconfig.thunderbird.net/v1.1/maroon.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/maskulin.dk",
"https://autoconfig.thunderbird.net/v1.1/me.com",
"https://autoconfig.thunderbird.net/v1.1/mebtel.net",
"https://autoconfig.thunderbird.net/v1.1/messagingengine.com",
"https://autoconfig.thunderbird.net/v1.1/mexicomail.com",
"https://autoconfig.thunderbird.net/v1.1/min-postkasse.dk",
"https://autoconfig.thunderbird.net/v1.1/mindless.com",
"https://autoconfig.thunderbird.net/v1.1/mindspring.com",
"https://autoconfig.thunderbird.net/v1.1/minister.com",
"https://autoconfig.thunderbird.net/v1.1/minuet.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/miobox.jp",
"https://autoconfig.thunderbird.net/v1.1/miomio.jp",
"https://autoconfig.thunderbird.net/v1.1/ml.murakami.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/ml.shibata.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mnet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mobil.dk",
"https://autoconfig.thunderbird.net/v1.1/mobsters.com",
"https://autoconfig.thunderbird.net/v1.1/monarchy.com",
"https://autoconfig.thunderbird.net/v1.1/mopera.net",
"https://autoconfig.thunderbird.net/v1.1/moscowmail.com",
"https://autoconfig.thunderbird.net/v1.1/msn.com",
"https://autoconfig.thunderbird.net/v1.1/multiweb.nl",
"https://autoconfig.thunderbird.net/v1.1/munich.com",
"https://autoconfig.thunderbird.net/v1.1/musician.org",
"https://autoconfig.thunderbird.net/v1.1/muslim.com",
"https://autoconfig.thunderbird.net/v1.1/musling.dk",
"https://autoconfig.thunderbird.net/v1.1/mx1.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx2.et.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx2.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx2.wt.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx3.et.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx3.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx4.et.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx4.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx5.et.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx5.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx6.et.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx6.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx7.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx8.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx9.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx21.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx22.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx31.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx32.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx35.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx36.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx41.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx51.et.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx51.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx52.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx61.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx71.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx81.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx82.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mx91.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/mypec.eu",
"https://autoconfig.thunderbird.net/v1.1/myself.com",
"https://autoconfig.thunderbird.net/v1.1/narod.ru",
"https://autoconfig.thunderbird.net/v1.1/natteliv.dk",
"https://autoconfig.thunderbird.net/v1.1/navy.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/netbruger.dk",
"https://autoconfig.thunderbird.net/v1.1/netscape.net",
"https://autoconfig.thunderbird.net/v1.1/neuf.fr",
"https://autoconfig.thunderbird.net/v1.1/newyork.usa.com",
"https://autoconfig.thunderbird.net/v1.1/nifty.com",
"https://autoconfig.thunderbird.net/v1.1/nn.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/nsat.jp",
"https://autoconfig.thunderbird.net/v1.1/ntlworld.com",
"https://autoconfig.thunderbird.net/v1.1/null.net",
"https://autoconfig.thunderbird.net/v1.1/nvbell.net",
"https://autoconfig.thunderbird.net/v1.1/nycmail.com",
"https://autoconfig.thunderbird.net/v1.1/o2.pl",
"https://autoconfig.thunderbird.net/v1.1/oath.com",
"https://autoconfig.thunderbird.net/v1.1/ocn.ad.jp",
"https://autoconfig.thunderbird.net/v1.1/ocn.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/olive.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/one.com",
"https://autoconfig.thunderbird.net/v1.1/one.cz",
"https://autoconfig.thunderbird.net/v1.1/onet.eu",
"https://autoconfig.thunderbird.net/v1.1/onet.pl",
"https://autoconfig.thunderbird.net/v1.1/online.de",
"https://autoconfig.thunderbird.net/v1.1/onlinehome.de",
"https://autoconfig.thunderbird.net/v1.1/op.pl",
"https://autoconfig.thunderbird.net/v1.1/opal.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/optician.com",
"https://autoconfig.thunderbird.net/v1.1/orange.fr",
"https://autoconfig.thunderbird.net/v1.1/orange.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/orchid.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/outlook.com",
"https://autoconfig.thunderbird.net/v1.1/ovh.net",
"https://autoconfig.thunderbird.net/v1.1/pacbell.net",
"https://autoconfig.thunderbird.net/v1.1/pacificwest.com",
"https://autoconfig.thunderbird.net/v1.1/pal.kijimadaira.jp",
"https://autoconfig.thunderbird.net/v1.1/palette.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/parabox.or.jp",
"https://autoconfig.thunderbird.net/v1.1/pdx.edu",
"https://autoconfig.thunderbird.net/v1.1/peach.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/pec.it",
"https://autoconfig.thunderbird.net/v1.1/pedal.dk",
"https://autoconfig.thunderbird.net/v1.1/pengemand.dk",
"https://autoconfig.thunderbird.net/v1.1/peoplepc.com",
"https://autoconfig.thunderbird.net/v1.1/petlover.com",
"https://autoconfig.thunderbird.net/v1.1/photographer.net",
"https://autoconfig.thunderbird.net/v1.1/playful.com",
"https://autoconfig.thunderbird.net/v1.1/plum.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/po.dcn.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/po.gunmanet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/po.gunmanet.or.jp",
"https://autoconfig.thunderbird.net/v1.1/po.wind.co.jp",
"https://autoconfig.thunderbird.net/v1.1/po.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/po.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/pobox.com",
"https://autoconfig.thunderbird.net/v1.1/poczta.onet.eu",
"https://autoconfig.thunderbird.net/v1.1/poczta.onet.pl",
"https://autoconfig.thunderbird.net/v1.1/poetic.com",
"https://autoconfig.thunderbird.net/v1.1/pokerface.dk",
"https://autoconfig.thunderbird.net/v1.1/politician.com",
"https://autoconfig.thunderbird.net/v1.1/polka.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/pop.shibata.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/popstar.com",
"https://autoconfig.thunderbird.net/v1.1/post.com",
"https://autoconfig.thunderbird.net/v1.1/post.cybercity.dk",
"https://autoconfig.thunderbird.net/v1.1/post.cz",
"https://autoconfig.thunderbird.net/v1.1/post.dia.dk",
"https://autoconfig.thunderbird.net/v1.1/posteo.at",
"https://autoconfig.thunderbird.net/v1.1/posteo.ch",
"https://autoconfig.thunderbird.net/v1.1/posteo.de",
"https://autoconfig.thunderbird.net/v1.1/posteo.eu",
"https://autoconfig.thunderbird.net/v1.1/posteo.org",
"https://autoconfig.thunderbird.net/v1.1/postman.dk",
"https://autoconfig.thunderbird.net/v1.1/pp.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/presidency.com",
"https://autoconfig.thunderbird.net/v1.1/priest.com",
"https://autoconfig.thunderbird.net/v1.1/privat.dia.dk",
"https://autoconfig.thunderbird.net/v1.1/privatmail.dk",
"https://autoconfig.thunderbird.net/v1.1/prodigy.net",
"https://autoconfig.thunderbird.net/v1.1/programmer.net",
"https://autoconfig.thunderbird.net/v1.1/prokonto.pl",
"https://autoconfig.thunderbird.net/v1.1/proximus.be",
"https://autoconfig.thunderbird.net/v1.1/ptd.net",
"https://autoconfig.thunderbird.net/v1.1/publicist.com",
"https://autoconfig.thunderbird.net/v1.1/purple.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/q.com",
"https://autoconfig.thunderbird.net/v1.1/qq.com",
"https://autoconfig.thunderbird.net/v1.1/quake.dk",
"https://autoconfig.thunderbird.net/v1.1/quicknet.nl",
"https://autoconfig.thunderbird.net/v1.1/rainbow.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/rambler.ru",
"https://autoconfig.thunderbird.net/v1.1/razcall.com",
"https://autoconfig.thunderbird.net/v1.1/razcall.nl",
"https://autoconfig.thunderbird.net/v1.1/ready.dk",
"https://autoconfig.thunderbird.net/v1.1/realtyagent.com",
"https://autoconfig.thunderbird.net/v1.1/reborn.com",
"https://autoconfig.thunderbird.net/v1.1/red.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/reggaefan.com",
"https://autoconfig.thunderbird.net/v1.1/religious.com",
"https://autoconfig.thunderbird.net/v1.1/repairman.com",
"https://autoconfig.thunderbird.net/v1.1/representative.com",
"https://autoconfig.thunderbird.net/v1.1/republika.pl",
"https://autoconfig.thunderbird.net/v1.1/rescueteam.com",
"https://autoconfig.thunderbird.net/v1.1/revenue.com",
"https://autoconfig.thunderbird.net/v1.1/rmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/rocketmail.com",
"https://autoconfig.thunderbird.net/v1.1/rocketship.com",
"https://autoconfig.thunderbird.net/v1.1/rockfan.com",
"https://autoconfig.thunderbird.net/v1.1/rome.com",
"https://autoconfig.thunderbird.net/v1.1/rondo.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/rose.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/rouge.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/royal.net",
"https://autoconfig.thunderbird.net/v1.1/rr.com",
"https://autoconfig.thunderbird.net/v1.1/rr.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/ruby.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/ruhrnet-online.de",
"https://autoconfig.thunderbird.net/v1.1/runestone.net",
"https://autoconfig.thunderbird.net/v1.1/rzone.de",
"https://autoconfig.thunderbird.net/v1.1/saintly.com",
"https://autoconfig.thunderbird.net/v1.1/sakunet.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/salesperson.net",
"https://autoconfig.thunderbird.net/v1.1/sanfranmail.com",
"https://autoconfig.thunderbird.net/v1.1/sbcglobal.net",
"https://autoconfig.thunderbird.net/v1.1/schlund.de",
"https://autoconfig.thunderbird.net/v1.1/scientist.com",
"https://autoconfig.thunderbird.net/v1.1/scotlandmail.com",
"https://autoconfig.thunderbird.net/v1.1/sea.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/secret.dk",
"https://autoconfig.thunderbird.net/v1.1/secretary.net",
"https://autoconfig.thunderbird.net/v1.1/secureserver.net",
"https://autoconfig.thunderbird.net/v1.1/seductive.com",
"https://autoconfig.thunderbird.net/v1.1/sepia.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/serenade.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/seznam.cz",
"https://autoconfig.thunderbird.net/v1.1/sfr.fr",
"https://autoconfig.thunderbird.net/v1.1/silk.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/silver.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/singapore.com",
"https://autoconfig.thunderbird.net/v1.1/sky.com",
"https://autoconfig.thunderbird.net/v1.1/sky.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/skynet.be",
"https://autoconfig.thunderbird.net/v1.1/sleepy.dk",
"https://autoconfig.thunderbird.net/v1.1/smail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/smtp.cz",
"https://autoconfig.thunderbird.net/v1.1/snakebite.com",
"https://autoconfig.thunderbird.net/v1.1/snet.net",
"https://autoconfig.thunderbird.net/v1.1/snow.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/so.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/so.wind.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/sofort-start.de",
"https://autoconfig.thunderbird.net/v1.1/sofort-surf.de",
"https://autoconfig.thunderbird.net/v1.1/sofortstart.de",
"https://autoconfig.thunderbird.net/v1.1/sofortsurf.de",
"https://autoconfig.thunderbird.net/v1.1/sonata.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/songwriter.net",
"https://autoconfig.thunderbird.net/v1.1/soon.com",
"https://autoconfig.thunderbird.net/v1.1/spainmail.com",
"https://autoconfig.thunderbird.net/v1.1/spoluzaci.cz",
"https://autoconfig.thunderbird.net/v1.1/sporty.dk",
"https://autoconfig.thunderbird.net/v1.1/ss.iij4u.or.jp",
"https://autoconfig.thunderbird.net/v1.1/strato.de",
"https://autoconfig.thunderbird.net/v1.1/studenti.univr.it",
"https://autoconfig.thunderbird.net/v1.1/suite.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/superbruger.dk",
"https://autoconfig.thunderbird.net/v1.1/swbell.net",
"https://autoconfig.thunderbird.net/v1.1/sympatico.ca",
"https://autoconfig.thunderbird.net/v1.1/symphony.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/t-online.de",
"https://autoconfig.thunderbird.net/v1.1/talent.dk",
"https://autoconfig.thunderbird.net/v1.1/talk21.com",
"https://autoconfig.thunderbird.net/v1.1/tanke.dk",
"https://autoconfig.thunderbird.net/v1.1/taupe.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/taxidriver.dk",
"https://autoconfig.thunderbird.net/v1.1/teachers.org",
"https://autoconfig.thunderbird.net/v1.1/techie.com",
"https://autoconfig.thunderbird.net/v1.1/technologist.com",
"https://autoconfig.thunderbird.net/v1.1/teens.dk",
"https://autoconfig.thunderbird.net/v1.1/teknik.dk",
"https://autoconfig.thunderbird.net/v1.1/telebel.de",
"https://autoconfig.thunderbird.net/v1.1/telelev.de",
"https://autoconfig.thunderbird.net/v1.1/teleos-web.de",
"https://autoconfig.thunderbird.net/v1.1/telstra.com",
"https://autoconfig.thunderbird.net/v1.1/terra.es",
"https://autoconfig.thunderbird.net/v1.1/texas.usa.com",
"https://autoconfig.thunderbird.net/v1.1/thegame.com",
"https://autoconfig.thunderbird.net/v1.1/therapist.net",
"https://autoconfig.thunderbird.net/v1.1/thinline.cz",
"https://autoconfig.thunderbird.net/v1.1/tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/tiscali.cz",
"https://autoconfig.thunderbird.net/v1.1/tiscali.it",
"https://autoconfig.thunderbird.net/v1.1/tjekket.dk",
"https://autoconfig.thunderbird.net/v1.1/tlen.pl",
"https://autoconfig.thunderbird.net/v1.1/tmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/toccata.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/toke.com",
"https://autoconfig.thunderbird.net/v1.1/tokyo.com",
"https://autoconfig.thunderbird.net/v1.1/toothfairy.com",
"https://autoconfig.thunderbird.net/v1.1/topaz.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/traceroute.dk",
"https://autoconfig.thunderbird.net/v1.1/trio.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/tv.dk",
"https://autoconfig.thunderbird.net/v1.1/tvstar.com",
"https://autoconfig.thunderbird.net/v1.1/ugenstilbud.dk",
"https://autoconfig.thunderbird.net/v1.1/umail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/umich.edu",
"https://autoconfig.thunderbird.net/v1.1/umpire.com",
"https://autoconfig.thunderbird.net/v1.1/ungdom.dk",
"https://autoconfig.thunderbird.net/v1.1/uol.com.br",
"https://autoconfig.thunderbird.net/v1.1/upcmail.nl",
"https://autoconfig.thunderbird.net/v1.1/usa.com",
"https://autoconfig.thunderbird.net/v1.1/uymail.com",
"https://autoconfig.thunderbird.net/v1.1/verizon.net",
"https://autoconfig.thunderbird.net/v1.1/versanet.de",
"https://autoconfig.thunderbird.net/v1.1/versatel.de",
"https://autoconfig.thunderbird.net/v1.1/video.dk",
"https://autoconfig.thunderbird.net/v1.1/violet.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/vip.cybercity.dk",
"https://autoconfig.thunderbird.net/v1.1/virgin.net",
"https://autoconfig.thunderbird.net/v1.1/virginmedia.com",
"https://autoconfig.thunderbird.net/v1.1/vittig.dk",
"https://autoconfig.thunderbird.net/v1.1/vm.aikis.or.jp",
"https://autoconfig.thunderbird.net/v1.1/vmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/vp.pl",
"https://autoconfig.thunderbird.net/v1.1/vp.tiki.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/wallet.com",
"https://autoconfig.thunderbird.net/v1.1/waltz.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/wanadoo.fr",
"https://autoconfig.thunderbird.net/v1.1/wans.net",
"https://autoconfig.thunderbird.net/v1.1/wave.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/web.de",
"https://autoconfig.thunderbird.net/v1.1/webhuset.no",
"https://autoconfig.thunderbird.net/v1.1/webname.com",
"https://autoconfig.thunderbird.net/v1.1/weirdness.com",
"https://autoconfig.thunderbird.net/v1.1/white.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/who.net",
"https://autoconfig.thunderbird.net/v1.1/whoever.com",
"https://autoconfig.thunderbird.net/v1.1/wine.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/winning.com",
"https://autoconfig.thunderbird.net/v1.1/witty.com",
"https://autoconfig.thunderbird.net/v1.1/wmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/wo.cz",
"https://autoconfig.thunderbird.net/v1.1/wol.dk",
"https://autoconfig.thunderbird.net/v1.1/worker.com",
"https://autoconfig.thunderbird.net/v1.1/workmail.com",
"https://autoconfig.thunderbird.net/v1.1/worldmail.cz",
"https://autoconfig.thunderbird.net/v1.1/worldonline.cz",
"https://autoconfig.thunderbird.net/v1.1/worldonline.dk",
"https://autoconfig.thunderbird.net/v1.1/wp.pl",
"https://autoconfig.thunderbird.net/v1.1/writeme.com",
"https://autoconfig.thunderbird.net/v1.1/x-il.jp",
"https://autoconfig.thunderbird.net/v1.1/xmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/xp.wind.jp",
"https://autoconfig.thunderbird.net/v1.1/xpost.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/xs4all.nl",
"https://autoconfig.thunderbird.net/v1.1/xtra.co.nz",
"https://autoconfig.thunderbird.net/v1.1/ya.ru",
"https://autoconfig.thunderbird.net/v1.1/yahoo.co.jp",
"https://autoconfig.thunderbird.net/v1.1/yahoo.co.nz",
"https://autoconfig.thunderbird.net/v1.1/yahoo.co.uk",
"https://autoconfig.thunderbird.net/v1.1/yahoo.com",
"https://autoconfig.thunderbird.net/v1.1/yahoo.com.ar",
"https://autoconfig.thunderbird.net/v1.1/yahoo.com.au",
"https://autoconfig.thunderbird.net/v1.1/yahoo.com.br",
"https://autoconfig.thunderbird.net/v1.1/yahoo.com.mx",
"https://autoconfig.thunderbird.net/v1.1/yahoo.de",
"https://autoconfig.thunderbird.net/v1.1/yahoo.es",
"https://autoconfig.thunderbird.net/v1.1/yahoo.fr",
"https://autoconfig.thunderbird.net/v1.1/yahoo.it",
"https://autoconfig.thunderbird.net/v1.1/yahoo.se",
"https://autoconfig.thunderbird.net/v1.1/yahoodns.net",
"https://autoconfig.thunderbird.net/v1.1/yandex.by",
"https://autoconfig.thunderbird.net/v1.1/yandex.com",
"https://autoconfig.thunderbird.net/v1.1/yandex.kz",
"https://autoconfig.thunderbird.net/v1.1/yandex.net",
"https://autoconfig.thunderbird.net/v1.1/yandex.ru",
"https://autoconfig.thunderbird.net/v1.1/yandex.ua",
"https://autoconfig.thunderbird.net/v1.1/ybb.ne.jp",
"https://autoconfig.thunderbird.net/v1.1/yeah.net",
"https://autoconfig.thunderbird.net/v1.1/yellow.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/ymail.com",
"https://autoconfig.thunderbird.net/v1.1/ymail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/yours.com",
"https://autoconfig.thunderbird.net/v1.1/ypost.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/zeelandnet.nl",
"https://autoconfig.thunderbird.net/v1.1/zeggis.com",
"https://autoconfig.thunderbird.net/v1.1/zeggis.nl",
"https://autoconfig.thunderbird.net/v1.1/ziggo.nl",
"https://autoconfig.thunderbird.net/v1.1/ziggomail.com",
"https://autoconfig.thunderbird.net/v1.1/zinders.nl",
"https://autoconfig.thunderbird.net/v1.1/zmail.plala.or.jp",
"https://autoconfig.thunderbird.net/v1.1/zoho.com",
"https://autoconfig.thunderbird.net/v1.1/zohomail.com",
"https://autoconfig.thunderbird.net/v1.1/zpost.plala.or.jp",
]

const ispdb = {};
const fs = require('fs')
const util = require('util');
const parseXML = require('xml2js').parseString;
const request = require('request');
let numProcessed = 0;
Promise.all(domains.map((domain) => {
  return new Promise((resolve, reject) => {
    return request.get(domain, (err, resp, body) => {
      numProcessed += 1;
      console.log(`[${numProcessed}/${domains.length}] Processed: ${domain}`)
      return parseXML(body, function (err, result) {
        return resolve(result);
      });
    })
  })
})).then((allDomainData) => {
/**
 * > [ { clientConfig:
     { '$': { version: '1.1' },
       emailProvider:
        [ { '$': { id: 'googlemail.com' },
            domain:
             [ 'gmail.com',
               'googlemail.com',
               'google.com',
               'jazztel.es',
               [length]: 4 ],
            displayName: [ 'Google Mail', [length]: 1 ],
            displayShortName: [ 'GMail', [length]: 1 ],
            incomingServer:
             [ { '$': { type: 'imap' },
                 hostname: [ 'imap.gmail.com', [length]: 1 ],
                 port: [ '993', [length]: 1 ],
                 socketType: [ 'SSL', [length]: 1 ],
                 username: [ '%EMAILADDRESS%', [length]: 1 ],
                 authentication: [ 'OAuth2', 'password-cleartext', [length]: 2 ] },
               { '$': { type: 'pop3' },
                 hostname: [ 'pop.gmail.com', [length]: 1 ],
                 port: [ '995', [length]: 1 ],
                 socketType: [ 'SSL', [length]: 1 ],
                 username: [ '%EMAILADDRESS%', [length]: 1 ],
                 authentication: [ 'password-cleartext', [length]: 1 ],
                 pop3: [ [Object], [length]: 1 ] },
               [length]: 2 ],
            outgoingServer:
             [ { '$': { type: 'smtp' },
                 hostname: [ 'smtp.gmail.com', [length]: 1 ],
                 port: [ '465', [length]: 1 ],
                 socketType: [ 'SSL', [length]: 1 ],
                 username: [ '%EMAILADDRESS%', [length]: 1 ],
                 authentication: [ 'OAuth2', 'password-cleartext', [length]: 2 ] },
               [length]: 1 ],
            enable:
             [ { '$': { visiturl: 'https://mail.google.com/mail/?ui=2&shva=1#settings/fwdandpop' },
                 instruction: [ 'You need to enable IMAP access', [length]: 1 ] },
               [length]: 1 ],
            documentation:
             [ { '$': { url: 'http://mail.google.com/support/bin/answer.py?answer=13273' },
                 descr: [ 'How to enable IMAP/POP3 in GMail', [length]: 1 ] },
               { '$': { url: 'http://mail.google.com/support/bin/topic.py?topic=12806' },
                 descr: [ 'How to configure email clients for IMAP', [length]: 1 ] },
               { '$': { url: 'http://mail.google.com/support/bin/topic.py?topic=12805' },
                 descr: [ 'How to configure email clients for POP3', [length]: 1 ] },
               { '$': { url: 'http://mail.google.com/support/bin/answer.py?answer=86399' },
                 descr: [ 'How to configure TB 2.0 for POP3', [length]: 1 ] },
               [length]: 4 ] },
          [length]: 1 ],
       webMail:
        [ { loginPage:
             [ { '$': { url: 'https://accounts.google.com/ServiceLogin?service=mail&continue=http://mail.google.com/mail/' } },
               [length]: 1 ],
            loginPageInfo:
             [ { '$': { url: 'https://accounts.google.com/ServiceLogin?service=mail&continue=http://mail.google.com/mail/' },
                 username: [ '%EMAILADDRESS%', [length]: 1 ],
                 usernameField: [ [Object], [length]: 1 ],
                 passwordField: [ [Object], [length]: 1 ],
                 loginButton: [ [Object], [length]: 1 ] },
               [length]: 1 ] },
          [length]: 1 ] } },
  [length]: 1 ]
 */
  // console.log(util.inspect(domainData, true, depth=7, colorize=true));
  for (const domainData of allDomainData) {
    if (!domainData) {
      console.error("No domain data")
      console.log(util.inspect(domainData, true, depth=7, colorize=true));
      continue;
    };
    const provider = ((domainData.clientConfig || {}).emailProvider || [])[0];
    if (!provider) {
      console.error("No provider")
      console.log(util.inspect(domainData, true, depth=7, colorize=true));
      continue;
    };
    if (!provider.incomingServer) {
      console.error("No incoming server")
      console.log(util.inspect(domainData, true, depth=7, colorize=true));
      continue;
    };
    if (!provider.outgoingServer) {
      console.error("No outgoing server")
      console.log(util.inspect(domainData, true, depth=7, colorize=true));
      continue;
    };

    const imapSettings = provider.incomingServer.filter((s = {}) => (s.$ || {}).type === "imap")[0] || {}
    const smtpSettings = provider.outgoingServer.filter((s = {}) => (s.$ || {}).type === "smtp")[0] || {}
    const enableSteps = (provider.enable || []).map((e = {}) => {
      const instr = (e.instruction || []).map((x = {}) => {
        if (typeof x === "string") return x
        return x._
      })
      return {
        url: (e.$ || {}).visiturl,
        label: instr.join(", ")}
    })
    const documentation = (provider.documentation || []).map((d = {}) => {
      const descr = (d.descr || []).map((x = {}) => {
        if (typeof x === "string") return x
        return x._
      })
      return {
        url: (d.$ || {}).url,
        label: descr.join(", ")
      }
    })

    ISPDBToNylas = {
      "SSL": "SSL / TLS",
      "STARTTLS": "STARTTLS",
      "plain": "none",
      "%EMAILADDRESS%": "email",
      "%EMAILLOCALPART%": "email-without-domain",
    }

    for (const domain of provider.domain) {
      ispdb[domain] = {
        display_name: provider.displayName[0],
        display_short_name: provider.displayShortName[0],
        imap_host: (imapSettings.hostname || [])[0] || "",
        imap_port: (imapSettings.port || [])[0] || "",
        imap_security: ISPDBToNylas[(imapSettings.socketType || [])[0]] || "SSL / TLS",
        imap_user_format: ISPDBToNylas[(imapSettings.username || [])[0]] || "email",
        imap_authentication: imapSettings.authentication,
        imap_restriction: imapSettings.restriction,
        smtp_host: (smtpSettings.hostname || [])[0] || "",
        smtp_port: (smtpSettings.port || [])[0] || "",
        smtp_security: ISPDBToNylas[(smtpSettings.socketType || [])[0]] || "SSL / TLS",
        smtp_user_format: ISPDBToNylas[(smtpSettings.username || [])[0]] || "email",
        smtp_authentication: smtpSettings.authentication,
        smtp_restriction: smtpSettings.restriction,
        enable_steps: enableSteps,
        documentation: documentation,
      }
    }
  }

  const oldNylasSettings = require("./old-nylas-settings.json");
  for (const dn of Object.keys(oldNylasSettings)) {
    let settings = oldNylasSettings[dn]
    if (settings.alias) {
      settings = oldNylasSettings[settings.alias];
    }
    if (ispdb[dn]) {
      ispdb[dn] = Object.assign({}, ispdb[dn], settings)
    } else {
      ispdb[dn] = settings
    }
  }

  fs.writeFileSync("ispdb.json", JSON.stringify(ispdb, null, 2))
})
